library risk_engine.snapshot;

import 'client.dart';

final List<EngineEvent> SNAPSHOT_GAME_STARTED = [
new Welcome()..playerId = 2,
new PlayerJoined()..playerId = 1..name = "Paul McCartney"..avatar = "castro",
new PlayerJoined()..playerId = 2..name = "John Lennon"..avatar = "kadhafi",
new GameStarted()..armies = 40..playersOrder = [2, 1],
new ArmyPlaced()..playerId = 1..country = "japan",
new ArmyPlaced()..playerId = 1..country = "ontario",
new ArmyPlaced()..playerId = 1..country = "india",
new ArmyPlaced()..playerId = 1..country = "ukraine",
new ArmyPlaced()..playerId = 1..country = "siberia",
new ArmyPlaced()..playerId = 1..country = "scandinavia",
new ArmyPlaced()..playerId = 1..country = "congo",
new ArmyPlaced()..playerId = 1..country = "greenland",
new ArmyPlaced()..playerId = 1..country = "western_australia",
new ArmyPlaced()..playerId = 1..country = "siam",
new ArmyPlaced()..playerId = 1..country = "alaska",
new ArmyPlaced()..playerId = 1..country = "ural",
new ArmyPlaced()..playerId = 1..country = "alberta",
new ArmyPlaced()..playerId = 1..country = "kamchatka",
new ArmyPlaced()..playerId = 1..country = "northwest_territory",
new ArmyPlaced()..playerId = 1..country = "indonesia",
new ArmyPlaced()..playerId = 1..country = "south_africa",
new ArmyPlaced()..playerId = 1..country = "argentina",
new ArmyPlaced()..playerId = 1..country = "china",
new ArmyPlaced()..playerId = 1..country = "quebec",
new ArmyPlaced()..playerId = 1..country = "eastern_united_states",
new ArmyPlaced()..playerId = 2..country = "egypt",
new ArmyPlaced()..playerId = 2..country = "peru",
new ArmyPlaced()..playerId = 2..country = "southern_europe",
new ArmyPlaced()..playerId = 2..country = "north_africa",
new ArmyPlaced()..playerId = 2..country = "afghanistan",
new ArmyPlaced()..playerId = 2..country = "yakursk",
new ArmyPlaced()..playerId = 2..country = "venezuela",
new ArmyPlaced()..playerId = 2..country = "central_america",
new ArmyPlaced()..playerId = 2..country = "eastern_australia",
new ArmyPlaced()..playerId = 2..country = "brazil",
new ArmyPlaced()..playerId = 2..country = "madagascar",
new ArmyPlaced()..playerId = 2..country = "mongolia",
new ArmyPlaced()..playerId = 2..country = "new_guinea",
new ArmyPlaced()..playerId = 2..country = "east_africa",
new ArmyPlaced()..playerId = 2..country = "western_europe",
new ArmyPlaced()..playerId = 2..country = "northern_europe",
new ArmyPlaced()..playerId = 2..country = "great_britain",
new ArmyPlaced()..playerId = 2..country = "middle_east",
new ArmyPlaced()..playerId = 2..country = "irkutsk",
new ArmyPlaced()..playerId = 2..country = "western_united_states",
new ArmyPlaced()..playerId = 2..country = "iceland",
new ArmyPlaced()..playerId = 1..country = "china",
new ArmyPlaced()..playerId = 1..country = "quebec",
new ArmyPlaced()..playerId = 1..country = "argentina",
new ArmyPlaced()..playerId = 1..country = "siam",
new ArmyPlaced()..playerId = 1..country = "ontario",
new ArmyPlaced()..playerId = 1..country = "eastern_united_states",
new ArmyPlaced()..playerId = 1..country = "siberia",
new ArmyPlaced()..playerId = 1..country = "western_australia",
new ArmyPlaced()..playerId = 1..country = "argentina",
new ArmyPlaced()..playerId = 1..country = "greenland",
new ArmyPlaced()..playerId = 1..country = "indonesia",
new ArmyPlaced()..playerId = 1..country = "ontario",
new ArmyPlaced()..playerId = 1..country = "ural",
new ArmyPlaced()..playerId = 1..country = "kamchatka",
new ArmyPlaced()..playerId = 1..country = "alberta",
new ArmyPlaced()..playerId = 1..country = "alberta",
new ArmyPlaced()..playerId = 1..country = "scandinavia",
new ArmyPlaced()..playerId = 1..country = "argentina",
new ArmyPlaced()..playerId = 1..country = "siberia",
new ArmyPlaced()..playerId = 2..country = "southern_europe",
new ArmyPlaced()..playerId = 2..country = "yakursk",
new ArmyPlaced()..playerId = 2..country = "afghanistan",
new ArmyPlaced()..playerId = 2..country = "iceland",
new ArmyPlaced()..playerId = 2..country = "iceland",
new ArmyPlaced()..playerId = 2..country = "north_africa",
new ArmyPlaced()..playerId = 2..country = "venezuela",
new ArmyPlaced()..playerId = 2..country = "iceland",
new ArmyPlaced()..playerId = 2..country = "great_britain",
new ArmyPlaced()..playerId = 2..country = "mongolia",
new ArmyPlaced()..playerId = 2..country = "madagascar",
new ArmyPlaced()..playerId = 2..country = "irkutsk",
new ArmyPlaced()..playerId = 2..country = "east_africa",
new ArmyPlaced()..playerId = 2..country = "brazil",
new ArmyPlaced()..playerId = 2..country = "central_america",
new ArmyPlaced()..playerId = 2..country = "venezuela",
new ArmyPlaced()..playerId = 2..country = "madagascar",
new ArmyPlaced()..playerId = 2..country = "peru",
new ArmyPlaced()..playerId = 2..country = "eastern_australia",
new SetupEnded(),
new NextPlayer()..playerId = 2..reinforcement = 7,
];

final List<EngineEvent> SNAPSHOT_GAME_ATTACK = SNAPSHOT_GAME_STARTED.toList()..addAll([
new ArmyPlaced()..playerId = 2..country = "eastern_australia",
new ArmyPlaced()..playerId = 2..country = "eastern_australia",
new ArmyPlaced()..playerId = 2..country = "eastern_australia",
new ArmyPlaced()..playerId = 2..country = "eastern_australia",
new ArmyPlaced()..playerId = 2..country = "eastern_australia",
new ArmyPlaced()..playerId = 2..country = "eastern_australia",
new ArmyPlaced()..playerId = 2..country = "eastern_australia",
new NextStep(),
]);