name: risk_engine
description: Provide logic for the two hour exercise Risk code lab.
dependencies:
  polymer: 0.9.5
  bootstrap_for_pub: ">=3.1.0 <3.2.0"
  morph: any
  http_server: any
dev_dependencies:
  unittest: any
  mock: any
