name: risk
description: A two hour exercise, based on the Risk game, to learn Polymer.dart.
dependencies:
  polymer: ">=0.15.5 <0.16.0"
  browser: any
  bootstrap_for_pub: ">=3.1.0 <3.2.0"
  morph: any
  http_server: any
  risk_engine:
    path: ../../risk_engine
dev_dependencies:
  unittest: any
  mock: any
transformers:
- polymer:
    entry_points: web/index.html
    inline_stylesheets:
      web/css/risk.css: false
      packages/bootstrap_for_pub/3.1.0/css/bootstrap.min.css: false
      packages/bootstrap_for_pub/3.1.0/css/bootstrap-theme.min.css: false