name: risk
description: A sample Polymer application
dependencies:
  polymer: any
  bootstrap_for_pub: ">=3.1.0+2 <4.0.0"
  morph: ">=0.8.2 <0.9.0"
  http_server: any
dev_dependencies:
  unittest: any
  mock: any
transformers:
- polymer:
    entry_points: web/index.html
